In [20]:
import h2o
from h2o.automl import H2OAutoML

In [21]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321. connected.

--------------------------  -----------------------------
H2O_cluster_uptime:         16 mins 36 secs
H2O_cluster_timezone:       America/Sao_Paulo
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.7
H2O_cluster_version_age:    2 months and 24 days
H2O_cluster_name:           H2O_from_python_Jaum_n8qndu
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    208.3 Mb
H2O_cluster_total_cores:    4
H2O_cluster_allowed_cores:  4
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.12.3 final
--------------------------  -----------------------------

In [22]:
data = h2o.import_file(r'C:\Users\Jaum\Desktop\CursoIA\4.Tópicos Avançados de Machine Learning\insurance.csv')

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [23]:
data

  C1  GoodStudent    Age         SocioEcon    RiskAversion    VehicleYear    ThisCarDam    RuggedAuto    Accident    MakeModel    DrivQuality    Mileage     Antilock    DrivingSkill    SeniorTrain    ThisCarCost    Theft    CarValue    HomeBase    AntiTheft    PropCost     OtherCarCost    OtherCar    MedCost    Cushioning    Airbag    ILiCost    DrivHist
----  -------------  ----------  -----------  --------------  -------------  ------------  ------------  ----------  -----------  -------------  ----------  ----------  --------------  -------------  -------------  -------  ----------  ----------  -----------  -----------  --------------  ----------  ---------  ------------  --------  ---------  ----------
   1  False          Adult       Prole        Adventurous     Older          Moderate      EggShell      Mild        Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        False        TenThou      Thousand        True        Thousand   Poor          False     Thousand   Many
   2  False          Senior      Prole        Cautious        Current        None          Football      None        Economy      Normal         TwentyThou  False       Normal          True           Thousand       False    TenThou     City        True         Thousand     Thousand        True        Thousand   Good          True      Thousand   Zero
   3  False          Senior      UpperMiddle  Psychopath      Current        None          Football      None        FamilySedan  Excellent      Domino      True        Normal          False          Thousand       False    TwentyThou  City        False        Thousand     Thousand        False       Thousand   Good          True      Thousand   One
   4  False          Adolescent  Middle       Normal          Older          None          EggShell      None        Economy      Normal         FiftyThou   False       Normal          False          Thousand       False    FiveThou    Suburb      False        Thousand     Thousand        True        Thousand   Fair          False     Thousand   Zero
   5  False          Adolescent  Prole        Normal          Older          Moderate      Football      Moderate    Economy      Poor           FiftyThou   False       SubStandard     False          TenThou        False    FiveThou    City        False        TenThou      Thousand        False       Thousand   Fair          False     Thousand   Many
   6  False          Adult       UpperMiddle  Normal          Current        Moderate      EggShell      Moderate    SportsCar    Poor           FiftyThou   True        SubStandard     False          HundredThou    False    TwentyThou  Suburb      True         HundredThou  HundredThou     True        TenThou    Poor          True      Thousand   Many
   7  False          Senior      UpperMiddle  Normal          Current        Mild          Football      Mild        Economy      Poor           FiveThou    False       SubStandard     False          TenThou        False    TenThou     Secure      True         TenThou      Thousand        False       Thousand   Excellent     True      Thousand   Many
   8  False          Adult       Prole        Normal          Older          Severe        EggShell      Severe      Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    TenThou     City        False        Million      HundredThou     True        Thousand   Fair          False     Thousand   Many
   9  False          Adult       Prole        Normal          Older          Severe        EggShell      Severe      Economy      Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        False        HundredThou  TenThou         False       TenThou    Poor          False     Thousand   Many
  10  True           Adolescent  Prole        Cautious        Older          Severe        Football      Severe      FamilySedan  Poor           TwentyThou  False       SubStandard     False          TenThou        False    FiveThou    City        True         HundredThou  HundredThou     True        Thousand   Good          False     Thousand   Many
[20000 rows x 28 columns]

In [24]:
data = data.drop('C1')

In [25]:
treino, teste = data.split_frame(ratios=[0.7], seed=0)

In [26]:
model_automl = H2OAutoML(max_runtime_secs=180, sort_metric='AUTO')
model_automl.train(y='Accident', training_frame=treino)

AutoML progress: |█
17:18:03.925: AutoML: XGBoost is not available; skipping it.
17:18:04.670: GLM_1_AutoML_2_20250620_171803 [GLM def_1] failed: java.lang.ArrayIndexOutOfBoundsException: 83

██████████████████████████████████████████████████████████████| (done) 100%

Model Details
=============
H2OStackedEnsembleEstimator : Stacked Ensemble
Model Key: StackedEnsemble_AllModels_1_AutoML_2_20250620_171803


Model Summary for Stacked Ensemble:
key                                   value
------------------------------------  ----------------
Stacking strategy                     cross_validation
Number of base models (used / total)  3/5
# GBM base models (used / total)      2/4
# DRF base models (used / total)      1/1
Metalearner algorithm                 GLM
Metalearner fold assignment scheme    Random
Metalearner nfolds                    5
Metalearner fold_column
Custom metalearner hyperparameters    None

ModelMetricsMultinomialGLM: stackedensemble
** Reported on train data. **

MSE: 0.026654771264734187
RMSE: 0.16326289004159575
LogLoss: 0.09053201262261225
Null degrees of freedom: 9985
Residual degrees of freedom: 9958
Null deviance: 18164.326344203437
Residual deviance: 1808.1053560988119
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
Mild    Moderate    None    Severe    Error        Rate
------  ----------  ------  --------  -----------  -----------
723     41          118     1         0.1812       160 / 883
27      662         2       117       0.180693     146 / 808
5       0           7123    0         0.000701459  5 / 7.128
0       28          0       1139      0.0239931    28 / 1.167
755     731         7243    1257      0.0339475    339 / 9.986

Top-4 Hit Ratios:
k    hit_ratio
---  -----------
1    0.966052
2    0.999499
3    1
4    1

ModelMetricsMultinomialGLM: stackedensemble
** Reported on cross-validation data. **

MSE: 0.03950379425725475
RMSE: 0.1987556144043603
LogLoss: 0.1362359867121734
Null degrees of freedom: 14063
Residual degrees of freedom: 14035
Null deviance: 25521.800614182997
Residual deviance: 3832.0458342400134
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
Mild    Moderate    None    Severe    Error       Rate
------  ----------  ------  --------  ----------  ------------
915     101         202     4         0.251227    307 / 1.222
59      842         4       223       0.253546    286 / 1.128
31      0           10021   0         0.00308396  31 / 10.052
1       92          0       1569      0.0559567   93 / 1.662
1006    1035        10227   1796      0.0509812   717 / 14.064

Top-4 Hit Ratios:
k    hit_ratio
---  -----------
1    0.949019
2    0.998436
3    0.999787
4    1

Cross-Validation Metrics Summary:
                         mean       sd          cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
-----------------------  ---------  ----------  ------------  ------------  ------------  ------------  ------------
accuracy                 0.949089   0.00544303  0.949875      0.954413      0.953945      0.945315      0.941897
aic                      nan        0           nan           nan           nan           nan           nan
auc                      nan        0           nan           nan           nan           nan           nan
err                      0.050911   0.00544303  0.0501253     0.0455872     0.046055      0.0546848     0.0581029
err_count                143.4      17.7003     140           125           129           157           166
loglikelihood            0          0           0             0             0             0             0
logloss                  0.136113   0.00866144  0.13543       0.123776      0.13296       0.142374      0.146026
max_per_class_error      0.279239   0.0218313   0.256039      0.25974       0.279835      0.307407      0.293173
mean_per_class_accuracy  0.859719   0.0132735   0.864379      0.867132      0.870977      0.858754      0.83735
mean_per_class_error     0.140281   0.0132735   0.13562       0.132868      0.129023      0.141246      0.16265
mse                      0.0394589  0.0031076   0.039068      0.0352765     0.0379346     0.0423207     0.0426947
null_deviance            5104.36    162.163     5050.45       4865.34       5120.52       5300.14       5185.35
pr_auc                   nan        0           nan           nan           nan           nan           nan
r2                       0.925185   0.00557628  0.927226      0.931519      0.928544      0.919359      0.919279
residual_deviance        766.409    62.1972     756.513       678.787       744.841       817.509       834.395
rmse                     0.198518   0.00785596  0.197656      0.187821      0.194768      0.20572       0.206627

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [27]:
ranking =model_automl.leaderboard
ranking = ranking.as_data_frame()
ranking

C:\Users\Jaum\PycharmProjects\IA\.venv\Lib\site-packages\h2o\frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

,model_id,mean_per_class_error,logloss,rmse,mse
0,StackedEnsemble_AllModels_1_AutoML_2_20250620_...,0.140954,0.136236,0.198756,0.039504
1,GBM_1_AutoML_2_20250620_171803,0.141156,0.132751,0.195396,0.038180
2,StackedEnsemble_BestOfFamily_1_AutoML_2_202506...,0.141283,0.136383,0.198707,0.039485
3,GBM_2_AutoML_2_20250620_171803,0.142359,0.196470,0.222164,0.049357
4,GBM_4_AutoML_2_20250620_171803,0.142690,0.234516,0.240056,0.057627
5,GBM_3_AutoML_2_20250620_171803,0.143156,0.213303,0.231688,0.053679
6,DRF_1_AutoML_2_20250620_171803,0.151275,0.470468,0.212368,0.045100

In [28]:
prever = model_automl.leader.predict(teste)
prever

stackedensemble prediction progress: |███████████████████████████████████████████| (done) 100%

predict           Mild     Moderate         None       Severe
---------  -----------  -----------  -----------  -----------
None       0.000687599  4.525e-05    0.999233     3.36524e-05
Moderate   0.0106916    0.971799     0.000924358  0.0165848
Severe     0.00337442   0.0730487    0.000812555  0.922764
None       0.000852001  5.36699e-05  0.999054     4.00021e-05
Severe     0.0181222    0.459512     0.00487842   0.517487
None       0.00273863   0.000108179  0.997071     8.18882e-05
Mild       0.9697       0.0106947    0.0186924    0.000913226
None       0.00127754   0.000101547  0.99855      7.13663e-05
None       0.00193808   0.000268616  0.997708     8.56764e-05
Severe     0.00417551   0.179666     0.00120471   0.814954
[5936 rows x 5 columns]